package bowling

/**
  * This class represents a frame.
  * Note that here in case of a strike or a spare, an 11th frame is created to store the pins that corresponds to the one generated by the 10th frame.
  * @param _first Int that corresponds to the first pin as a result of the first roll of this Frame.
  * @param _second Option[Int] that corresponds to the second pin as a result of the second roll of this Frame. If _first is 10, _second=None. If the second pin was not rolled yet: second=None. If gutter: second=Some(0)
  */
case class Frame(val _first: Int, val _second: Option[Int]) {

  /**
    * Returns the first pin of the frame
    *
    * @return Int that corresponds to the first pin of the frame
    */
  def first: Int = this._first

  /**
    * Returns the second pin of the frame
    *
    * @return Int that corresponds to the second pin of the frame
    */
  def second: Option[Int] = this._second

  /**
    * Returns the type of the bonus of this frame, either:
    * Util.STRIKE: if a strike have been rolled;
    * Util.SPARE: if a spare have been rolled;
    * Util.NOTHING: if a neither a spare nor a strike have been rolled;
    * Util.NOTHING_YET: if a a strike was not rolled in the current frame;
    * @return String that corresponds to type of the bonus of acquired for this frame.
    */
  def getBonusType: String = {
    first match {
      case 10 => Util.STRIKE
      case _ => {
        if (first+second.getOrElse(0) ==10){
          Util.SPARE
        }
        else if (second.isEmpty) Util.NOTHING_YET else Util.NOTHING
      }
    }
  }

  /**
    * Gives the score gained by this single frame
    * @return Int that corresponds to the score gained by his frame.
    */
  def getScore: Int = {
    first match {
      case 10 => 10
      case _ => first+second.getOrElse(0)
    }
  }
}
